role_not_valid = "Invalid role."
required_field = {"required_field": lambda field: f"{field} is required."}
email_address_exist = "email address exist."
invalid_email_format = "Invalid email format. Please provide a valid email address."
password_not_valid = "Password must be at least 8 characters long and include letters, numbers, and special characters."
organization_name_required = "organization name is required."
email_and_otp_required = 'Email address and OTP are required.'
invalid_otp = 'Invalid or expired OTP.'
otp_failed_to_send = "Failed to send OTP."
email_failed_to_send_otp = "Error sending OTP email."
user_not_found = "User not found."
user_is_verified = "User is already verified. No OTP sent."